version: '3.6'

services:
  test_db:
    image: mongo
    volumes:
      - ./.data/dev_db:/data/db
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=dev_db
    restart: always
