version: '3.6'

services:
  test_db:
    image: mongo
    volumes:
      - ./.data/test_db:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test_db
    restart: always
