# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: docker-compose -f docker-compose.test.yaml up -d
      - run: set MONGO_TEST_URI='mongodb://localhost:27018/test_db'
      - run: set MONGO_URI='mongodb://localhost:27018/test_db'
      - run: set ACCESS_KEY='accessKey'
      - run: set JWT_SECRET='secret'
      - run: set NODE_ENV='test'
      - run: yarn test:e2e
      - run: docker-compose -f docker-compose.test.yaml down
